### ISSUE TITLE
Нужно купить огнетушители:

### ISSUE THREAD

**Issue by gochankot** [boringplace/projects#13]
Нужно купить огнетушители:
- 3 углекислотных на 2 кг. (два в зал, один - на кухню);
- 1 порошковый на 3 кг. (в мастерскую).

// Move /orgs/sarfsc/projects/1: Original added by @mastersin

**Comment by ghost** [comment]
Из того, что я накопал по нормативам: Ставится 1 огнетушитель на 25 квадратов помещения. Расстояние до огнетушителя не должно превышать 20 метров. Порошковый в мастерскую ставим по той причине, что там может потребоваться тушение горючих газов, ЛВЖ и прочей гадости.

В основном помещении ситуация попроще, так что там пойдёт углекислота.
