### ISSUE TITLE
Software Freedom Day 2018

### ISSUE THREAD

**Issue by NIR-Ginko** [boringplace/projects#5]
3-я суббота сентября, 15 сентября 2018 года проводится Software Freedom Day. Необходимо разработать план мероприятий. Также скоро откроется регистрация событий на softwarefreedomday.org , надо будет перевести баннер, разместить на сайте и сделать ещё кучу всего полезного.

**Comment by ghost** [comment]
План действий:
- [X] Скачать шрифты [VDS](https://fontlibrary.org/en/font/vds) и [Averia](https://fontlibrary.org/en/font/averia/)
- [X] Скачать баннер http://wiki.softwarefreedomday.org/Promote?action=AttachFile&do=get&target=web-banner.svg
- [x] Локализовать баннер SFD.
- [x] Зарегистрироваться на сайте SFD, принять [Code of Conduct](http://wiki.softwarefreedomday.org/CodeOfConduct)
- [ ] Подписаться на список рассылки SFD и отправить баннеры в апстрим.
- [X] Добавить страницу команды [SarLUG](http://wiki.softwarefreedomday.org/2018/Russia/Saratov/SarLUG)'а на wiki SFD
- [x] Зарегистрировать мероприятие на сайте.
- [x] Разместить информацию на сайтах SarSFC и boringplace.
- [x] Разместить информацию о мероприятии в группе SarSFC и broingplace в VK.
- [x] Разработать план мероприятий.

**Comment by darkhilli** [comment]
Регистрация пока не открыта (https://www.softwarefreedomday.org/cgi-bin/register.py): 
> SFD Registration is not yet open. If you are interested in organizing an event for the next SFD celebration and want to be informed about registration opening the best way is surely to subscribe to one of our mailing lists, either sfd-discuss or announce. You can find the mailing list description page right here.
Подробности в рассылках: http://mail.sf-day.org/lists/listinfo

**Comment by darkhilli** [comment]
Добавил страницу команды на официальной wiki:
http://wiki.softwarefreedomday.org/2018/Russia/Saratov/SarLUG

**Comment by NIR-Ginko** [comment]
Предлагаю разбить страничку [Наши мероприятия](http://www.boringplace.org/events/) на две части: "предстоящие" и "отчёты о прошедших мероприятиях".
